[package]
name = "DocSense"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
serde = { version = "1.0.219" , features = ["derive"] }
serde_json = "1.0.140"
sqlite = "0.30.3"
sqlite3-sys = "0.14.0"
tiny_http = "0.12.0"
xml-rs = "0.8.26"
