name: DocSense CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpoppler-glib-dev pkg-config
        PKG_PATH=$(dpkg -L libpoppler-glib-dev | grep 'poppler-glib.pc' || true)
        echo "Found poppler-glib.pc at: $PKG_PATH"
        if [ -z "$PKG_PATH" ]; then
          echo "ERROR: poppler-glib.pc not found!" && exit 1
        fi
        export PKG_CONFIG_PATH=$(dirname $PKG_PATH)
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Verify pkg-config
      run: |
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}"
        pkg-config --modversion poppler-glib

    - name: Build (Debug)
      run: cargo build --verbose

    - name: Build (Release)
      run: cargo build --release --verbose